/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    AutocompleteMultiple: typeof import('./src/components/forms/AutocompleteMultiple.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BooleanField: typeof import('./src/components/forms/BooleanField.vue')['default']
    Button: typeof import('primevue/button')['default']
    CohortDashboard: typeof import('./src/components/cohort/CohortDashboard.vue')['default']
    CohortList: typeof import('./src/components/cohort/CohortList.vue')['default']
    Column: typeof import('primevue/column')['default']
    CourseList: typeof import('./src/components/course/CourseList.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DistrictList: typeof import('./src/components/district/DistrictList.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    DropDownField: typeof import('./src/components/forms/DropDownField.vue')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginProfile: typeof import('./src/components/topmenu/LoginProfile.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    Panel: typeof import('primevue/panel')['default']
    ProfileEdit: typeof import('./src/components/profile/ProfileEdit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('primevue/tag')['default']
    TeacherDashboard: typeof import('./src/components/teacher/TeacherDashboard.vue')['default']
    TeacherList: typeof import('./src/components/teacher/TeacherList.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TextAreaField: typeof import('./src/components/forms/TextAreaField.vue')['default']
    TextField: typeof import('./src/components/forms/TextField.vue')['default']
    ThemeToggle: typeof import('./src/components/topmenu/ThemeToggle.vue')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    TopMenu: typeof import('./src/components/topmenu/TopMenu.vue')['default']
    UserList: typeof import('./src/components/user/UserList.vue')['default']
  }
}
