/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutocompleteMultiple: typeof import('./src/components/forms/AutocompleteMultiple.vue')['default']
    BooleanField: typeof import('./src/components/forms/BooleanField.vue')['default']
    CohortDashboard: typeof import('./src/components/cohort/CohortDashboard.vue')['default']
    CohortList: typeof import('./src/components/cohort/CohortList.vue')['default']
    CourseList: typeof import('./src/components/course/CourseList.vue')['default']
    DistrictList: typeof import('./src/components/district/DistrictList.vue')['default']
    DropDownField: typeof import('./src/components/forms/DropDownField.vue')['default']
    LoginProfile: typeof import('./src/components/topmenu/LoginProfile.vue')['default']
    ProfileEdit: typeof import('./src/components/profile/ProfileEdit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeacherDashboard: typeof import('./src/components/teacher/TeacherDashboard.vue')['default']
    TeacherList: typeof import('./src/components/teacher/TeacherList.vue')['default']
    TextAreaField: typeof import('./src/components/forms/TextAreaField.vue')['default']
    TextField: typeof import('./src/components/forms/TextField.vue')['default']
    ThemeToggle: typeof import('./src/components/topmenu/ThemeToggle.vue')['default']
    TopMenu: typeof import('./src/components/topmenu/TopMenu.vue')['default']
    UserList: typeof import('./src/components/user/UserList.vue')['default']
  }
}
