import Model from './base.js'; // Ensure you include .js extension
import crypto from 'crypto';
import jwt from 'jsonwebtoken';
import logger from '../configs/logger.js'; // Ensure you include .js extension
import axios from 'axios';
import { parseStringPromise } from 'xml2js';
import util from 'node:util';
import objection from 'objection';

/**
 * @swagger
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       required:
 *         - eid
 *         - name
 *       properties:
 *         id:
 *           type: integer
 *           description: autogenerated id
 *         eid:
 *           type: string
 *           minLength: 3
 *           maxLength: 20
 *           description: K-State eID of the user
 *         name:
 *           type: string
 *           minLength: 3
 *           maxLength: 255
 *           description: the user's name
 *         roles:
 *           type: array
 *           items:
 *             $ref: '#/components/schemas/Role'
 *       example:
 *           id: 1
 *           eid: test-admin
 *           name: Test Administrator
 *           roles:
 *             - id: 1
 *               name: admin
 */

class User extends Model {
  // Table name is the only required property.
  static get tableName() {
    return 'users';
  }

  // Each model must have a column (or a set of columns) that uniquely
  // identifies the rows. The column(s) can be specified using the `idColumn`
  // property. `idColumn` returns `id` by default and doesn't need to be
  // specified unless the model's primary key is something else.
  static get idColumn() {
    return 'id';
  }

  static async findOrCreate(eid) {
    let user = await User.query().where('eid', eid).limit(1);
    // user not found - create user
    if (user.length === 0) {
      let name = eid;
      try {
        logger.debug('Looking up ' + eid + ' in K-State directory');
        const response = await axios.get(
          'https://k-state.edu/People/filter/eid=' + eid
        );
        const jsonstring = await parseStringPromise(response.data);
        for (const result of jsonstring.results.result) {
          if (eid === result.eid) {
            name = result.fn + ' ' + result.ln;
            logger.debug('Match Found! ' + name);
            break;
          }
        }
      } catch (error) {
        logger.error('Unable to query name from K-State directory!');
        logger.error(util.inspect(error));
      }
      user = [
        await User.query().insert({
          eid: eid,
          name: name,
        }),
      ];
      logger.info('User ' + eid + ' created');
    }
    return user[0];
  }

  static async findByRefreshToken(token) {
    let user = await User.query().where('refresh_token', token).limit(1);
    if (user.length === 0) {
      return null;
    }
    return user[0];
  }

  async updateRefreshToken() {
    let token = this.refresh_token;
    if (!token) {
      token = crypto.randomBytes(32).toString('hex');
      await this.$query().patch({
        refresh_token: token,
      });
    }
    const refresh_token = jwt.sign(
      {
        refresh_token: token,
      },
      process.env.TOKEN_SECRET,
      {
        expiresIn: '6h',
      }
    );
    return refresh_token;
  }

  async get_roles() {
    const roles = await this.$relatedQuery('roles').for(this.id).select('name');
    return roles.map((role) => role.name);
  }

  static async getToken(id) {
    let user = await User.query().findById(id);
    const refresh_token = await user.updateRefreshToken();
    const roles = await user.get_roles();
    const token = jwt.sign(
      {
        user_id: id,
        eid: user.eid,
        roles: roles,
        refresh_token: refresh_token,
      },
      process.env.TOKEN_SECRET,
      {
        expiresIn: '30m',
      }
    );
    return token;
  }

  static async clearRefreshToken(id) {
    await User.query().findById(id).patch({
      refresh_token: null,
    });
  }

  static get jsonSchema() {
    return {
      type: 'object',
      required: ['eid', 'name'],

      properties: {
        eid: { type: 'string', minLength: 3, maxLength: 20 },
        name: { type: 'string', minLength: 1, maxLength: 255 },
      },
    };
  }

  static get relationMappings() {
    const Role = require('./role.js'); // Ensure you include .js extension

    return {
      roles: {
        relation: Model.ManyToManyRelation,
        modelClass: Role,
        join: {
          from: 'users.id',
          through: {
            from: 'user_roles.user_id',
            to: 'user_roles.role_id',
          },
          to: 'roles.id',
        },
        filter: (builder) => builder.select('id', 'name'),
      },
    };
  }

  async $beforeInsert() {
    let user = await User.query().where('eid', this.eid).limit(1);
    // user not found - create user
    if (user.length !== 0) {
      throw new objection.ValidationError({
        message: 'eid should be unique',
        type: 'ModelValidation',
        data: {
          eid: [
            {
              message: 'this eID is already in use',
            },
          ],
        },
      });
    }
  }
}

export default User;
